### ISSUE TITLE
[Rule Tuning] Startup or Run Key Registry Modification

### ISSUE THREAD

**Issue by psanz-estc** [elastic/detection-rules#3357]
## Link to rule
https://www.elastic.co/guide/en/security/current/startup-or-run-key-registry-modification.html

## Description
Rule "Startup or Run Key Registration Modification" leads to a lot of false positives alerts in the rule due to the `registry.path`(ie MS Office using different registry keys for different users). 

One option would be to create exceptions based on some fields (such as `process.name`) but it is not clear if we would be allowing rogue binaries to go unnoticed./ 

## Example Data
In the capture below we can see `registry.path` and  `process.name`

Registry.path changes from user to user, so each alert is different
Creating exceptions based on `process.name` would open the door to non legit binaries going under the radar

**Comment by ibotello** [comment]
Example Data

![consultaelastic png](https://github.com/elastic/detection-rules/assets/87008515/67c208d5-d34c-4e63-8a1d-76a52b91a2d2)

**Comment by w0rk3r** [comment]
Hey @psanz-estc @ibotello, I've just pushed https://github.com/elastic/detection-rules/issues/3357 to solve the majority of the FPs that this rule is generating, let me know if you have any feedback on it ;)

And thanks for bringing this to our attention, we are doing a review on the entire ruleset as part of https://github.com/elastic/detection-rules/issues/3186, but do not hesitate to open a tuning issue in the repo if any rule is generating a considerable amount of FPs.

**Comment by psanz-estc** [comment]
hi @w0rk3r , even after upgrading to version 8.11.7 (released on Jan 25th) we still see quite a lot false positives for `Startup or Run Key Registration Modification` rule 

<img width="2195" alt="image" src="https://github.com/elastic/detection-rules/assets/44199691/2606aa23-d0be-4aef-9df5-1cf38099deeb">

As you can see in the image above, at least in this case, it seems it seems all related to `msedge.exe` (but could be circumstantial) .

Any chance this could be improved?
