### ISSUE TITLE
[Bug] upload-rule CLI Error: Missing argument

### ISSUE THREAD

**Issue by whilter** [elastic/detection-rules#407]
**Describe the bug**

**To Reproduce**
1. clone the repo
2.  python -m detection_rules kibana upload-rule -u user -p password -k my_kibana_url rules/some_rule.toml
3. See error
CLI Error (NoneType): Missing required --cloud-id or --kibana-url

**Expected behavior**
Rule uploaded.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Comment by brokensound77** [comment]
:wave: Hello @whilter, looks like this was resolved in #425. So you should be good to pull updates from main if you want to verify

**Comment by threat-punter** [comment]
@whilter - Did you get a chance to verify that it's working as expected? I'll keep the issue open for a few more days in case you're still experiencing issues 👍
